### ISSUE TITLE
`boring`'s armv7-linux builds fail

### ISSUE THREAD

**Issue by exquo** [exquo/signal-libs-build#13]
After the [BoringSSL](https://github.com/signalapp/boring) lib has been added as a dependency of `libsignal`, cross-compiling the latter fails for target `armv7-linux-gnueabihf`:
https://github.com/exquo/signal-libs-build/actions/runs/3411284904/jobs/5675310584

However, building the `boring` library itself for the same target in the same environment succeeds..
https://github.com/exquo/signal-libs-build/actions/runs/3411698940/jobs/5676237923

Asked upstream: https://github.com/signalapp/libsignal/issues/481#issuecomment-1306017143

**Comment by morph027** [comment]
Probably have a look here: https://github.com/signalapp/libsignal/issues/481

**Comment by r0perice** [comment]
Any updates on this ?

**Comment by morph027** [comment]
I've added a pull request to upstream boring ssl. Should be in the next libsignal release: https://github.com/signalapp/libsignal/labels/awaiting%20release

**Comment by exquo** [comment]
Thanks @morph027! 
I'll close this issue when the workflow automatically builds everything successfully on picking up the next upstream release.
In the meantime, I'll try to also add the `armv7` build object to the current release.

**Comment by bitboy85** [comment]
Do you have a release?

I currently added the older 0.18.1 version to the 0.21.1 jar file. seems to work, at least for sending

2 things for the documentation
I have a raspberry 4 and it uses arm7 platform (not aarch like described in the readme)
to get the old version into the jar file, use zip command WITHOUT u parameter

**Comment by morph027** [comment]
You can try the artifact from https://gitlab.com/packaging/libsignal-client/-/issues/2#note_1224620739

**Comment by exquo** [comment]
Thank you very much @morph027 for submitting the fix upstream! With it the new releases build for ARMv7 target again!
I've also [ran a workflow](https://github.com/exquo/signal-libs-build/actions/runs/4157059518) that added the `armv7-unknown-linux-gnueabihf` file to the [v0.21.1 release](https://github.com/exquo/signal-libs-build/releases/tag/libsignal-client_v0.21.1).
