### ISSUE TITLE
Signed builds?

### ISSUE THREAD

**Issue by orazioedoardo** [exquo/signal-libs-build#16]
signal-cli is currently signed, which is useful to avoid trusting HTTPS on every download, however libsignal releases are not. Since using a release means replacing a shared library, the security is reduced to that of libsignal. So I’m asking whether you could also sign libsignal release, automatically in the workflow files. If you agree, I recommend using [signify](https://github.com/aperezdc/signify) or just [ssh keys](https://www.agwa.name/blog/post/ssh_signatures). No GPG please as it requires a stateful keyring.

**Comment by orazioedoardo** [comment]
> What is the threat model?

Threat model is attacker with MITM capabilities via fraudulently obtained certificates, for example.

> I suspect if a user's TLS can not be trusted, then securing this repo's artifacts would be the least of their worries.

While it's true that users in one way of another have to trust it, security conscious software still try to reduce trust in it, by signing updates or pinning certificates.

> And for that goal, where would they get a signing key that they can trust?

Trust on first use (TOFU) mechanism. Import the key the first time the release is obtained, then use that key to validate going forward.

**Comment by exquo** [comment]
A user can save the certificate / public key of the domain on the first use, and verify it on subsequent downloads. The effort would be the same as with verifying the release signatures, and it would take care of the threat model you have outlined.
Additionally, with [Certificate Transparency](https://en.wikipedia.org/wiki/Certificate_Transparency) the likelihood of a mis-issued certificate going unnoticed is severely reduced.

**Comment by exquo** [comment]
Github's current certificate is valid for a year. And their public keys probably won't change after a certificate is renewed.

You can check any certificate on several of the Certificate Transparency [logs](https://certificate.transparency.dev/logs/), from different devices on different networks. Once you are reasonably sure you have a good certificate, save Github's public keys from it. From that point on, you can verify new connections using the public key, without trusting the CAs. It's basically a manually-operated certificate pinning. This would be no less secure than trusting a key with which Github Actions would sign this repo's releases.
