### ISSUE TITLE
fatal runtime error: failed to initiate panic, error 5

### ISSUE THREAD

**Issue by mitar** [exquo/signal-libs-build#18]
I am trying to run the [latest signal-cli v0.13.0](https://github.com/AsamK/signal-cli/releases/tag/v0.13.0) which requires libsignal-client version 0.39.2. I am running on x86_64 with Ubuntu 20.04.

So I downloaded `libsignal_jni.so-v0.40.1-x86_64-unknown-linux-gnu.tar.gz` and replaced:

```
zip -uj signal-cli-0.13.0/lib/libsignal-client-0.39.2.jar libsignal_jni.so
```

When I run signal-cli, I get the following error:

```
fatal runtime error: failed to initiate panic, error 5
Aborted (core dumped)
```

**Comment by zimtkeks** [comment]
I observed a similar issue with `signal-cli-0.13.0.tar.gz` and `libsignal_jni.so-v0.40.1-aarch64-unknown-linux-gnu.tar.gz` on my RPi4 when trying to run `signal-cli` in a docker container.
`fatal runtime error: failed to initiate panic, error 2152741936` (error code varies on retry)

**Comment by zimtkeks** [comment]
However, it _does_ work with `libsignal_jni.so-v0.40.0-aarch64-unknown-linux-gnu.tar.gz` on my end. :)

**Comment by mitar** [comment]
Ah. I tried only 0.39.2 and 0.40.1.

**Comment by exquo** [comment]
As you correctly say

> signal-cli v0.13.0 requires libsignal-client version 0.39.2

Any newer version of libsignal-client might not function correctly. Using `libsignal_jni.so` from

	libsignal_jni.so-v0.39.2-x86_64-unknown-linux-gnu.tar.gz

works for me. Please try again with this file, and if the problem persist, feel free to re-open the issue.
