### ISSUE TITLE
Doesn't work on my Linux (i686)

### ISSUE THREAD

**Issue by gcey** [exquo/signal-libs-build#2]
I used `https://github.com/exquo/signal-libs-build/releases/download/v0.8.4.1/signal-cli-v0.8.4.1-x86_64-Linux.tar.gz` and I got
```
OpenJDK Server VM warning: You have loaded library /tmp/resource17548792288693908275.so which might have disabled stack guard. The VM will try to fix the stack guard now.
It's highly recommended that you fix the library with 'execstack -c <libfile>', or link it with '-z noexecstack'.
WARN App - WARNING: Support for new group V2 is disabled, because the required native library dependency is missing: libzkgroup
Missing required native library dependency: libsignal-client
```
`uname -m` says `i686`

**Comment by exquo** [comment]
The signal-cli version you have downloaded is for x86_64 linux. To make it work on i686, download the two .so files with i686 in their names from the [release page](https://github.com/exquo/signal-libs-build/releases). Then use the instructions in <https://github.com/AsamK/signal-cli/wiki/Provide-native-lib-for-libsignal> to replace the x86_64 .so files inside the .jar archives with the i686 versions. 

Essentially, this means executing these commands:

	wget https://github.com/exquo/signal-libs-build/releases/download/v0.8.4.1/libzkgroup.so-v0.7.0-i686-unknown-linux-gnu.tar.gz
	wget https://github.com/exquo/signal-libs-build/releases/download/v0.8.4.1/libsignal_jni.so-v0.8.1-i686-unknown-linux-gnu.tar.gz
	tar -xzf libzkgroup.so-v0.7.0-i686-unknown-linux-gnu.tar.gz
	tar -xzf libsignal_jni.so-v0.8.1-i686-unknown-linux-gnu.tar.gz
	zip -u signal-cli-0.8.4.1/lib/zkgroup-java-0.7.0.jar  libzkgroup.so 
	zip -u signal-cli-0.8.4.1/lib/signal-client-java-0.8.1.jar  libsignal_jni.so
