### ISSUE TITLE
Suggestion: Graal native-image builds?

### ISSUE THREAD

**Issue by technillogue** [exquo/signal-libs-build#3]
It would be cool to be able to link people to the latest graal builds, I don't know if that might be a good fit for this repo?

**Comment by exquo** [comment]
I haven't yet tried GraalVM, but it might be worth looking into. Thanks!

**Comment by exquo** [comment]
There are GraalVM builds for amd64 and arm64 for Ubuntu and [Docker](https://gitlab.com/packaging/signal-cli/container_registry) available in
https://gitlab.com/packaging/signal-cli

**Comment by exquo** [comment]
Since [v0.11.4](https://github.com/AsamK/signal-cli/releases/tag/v0.11.4), signal-cli official releases have the native builds for linux as well.
