### ISSUE TITLE
libzkgroup / libsignal-client missing under cygwin

### ISSUE THREAD

**Issue by no2spc** [exquo/signal-libs-build#4]
I'm trying to get your prepacked 'signal-cli-v0.8.5-x86_64-Linux.tar.tz' up and running in Cygwin BASH under Windows10. And I'm stuck getting the error message that libzkgroup and libsignal-client are missing. Is there something I overlooked? I assumed that the pre-compiled Linux variants would also work 'out-of-the-box' also on the cygwin.

java -version: java version "14.0.2" 2020-07-14
uname -m : x86_64

Thanks, no2spc

**Comment by no2spc** [comment]
Using the same files ('signal-cli-v0.8.5-x86_64-Linux.tar.tz') under Ubuntu WSL2 running on the same Windows10 installation works fine.

**Comment by no2spc** [comment]
I was able to solve this using the Windows Version (signal-cli-v0.8.5-x86_64-Windows.tar.gz) and adding the DLL folder to the PATH using the following code (assuming that pwd is the dll Folder):
`export PATH=`pwd`:$PATH`

To make this permanently, add to the cygwin64\home\USER\.bash_profile the following line:

`export SIGNAL_DLL="/cygdrive/PATH/TO/dll"
export PATH="$SIGNAL_DLL:$PATH"`

**Comment by exquo** [comment]
The Linux versions of the rust libraries are compiled for the GNU libc (`glibc`) which is not available in cygwin (see its [FAQ](https://cygwin.com/faq/faq.html#faq.programming.glibc)).

Thanks for the tip about the `$PATH` for cygwin! For non-cygwin setups, one can use either the `…-Windows` package in PowerShell / Cmd, or the `…-Linux` version in WSL, as you've mentioned.
