### ISSUE TITLE
Instructions Missing

### ISSUE THREAD

**Issue by straussmaus** [exquo/signal-libs-build#6]
There is no indication that I saw where to put the .so file.  /usr/lib and /usr/local/lib are not the answer since when I do this and run signal-cli, I still get the error:

```
WARN ServiceConfig - Failed to call libsignal-client: /tmp/resourcexxxxxxxxx.so: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/resourcexxxxxxxxx.so)
Missing required native library dependency: libsignal-client
```

**Comment by exquo** [comment]
The `.so` files should be put inside the `.jar` archives. See the [How to use it section](https://github.com/exquo/signal-libs-build#how-to-use-it). What architecture is this for? (what's the output of `uname -a`?)

**Comment by straussmaus** [comment]
Architecture: x86_64

Hi, thank you.  I think the problem was I was not using your version of signal-cli.  


But I think you might want to fix this.  You say:
```
For Linux, MacOS and Windows on x86_64 processors, the binaries are packaged into signal-cli. Simply download a release for your platform and run it as usual.
```

But the file is `signal-cli-v0.9.0-x86_64-Linux.tar.gz`, and you do not run a tar.gz file.  But you said to `run` the file.

It would be better to say that you should extract, move to /opt/, and then create a symlink.  Maybe?
