### ISSUE TITLE
cargo error: "feature `resolver` is required"

### ISSUE THREAD

**Issue by egabosh** [exquo/signal-libs-build#7]
Moin,
getting the following error at build_jni.sh:
```
# ./build_jni.sh desktop'
cargo build -p libsignal-jni --release
error: failed to parse manifest at `/data-crypt/share/home/signal/libsignal-client/Cargo.toml`

Caused by:
  feature `resolver` is required

  consider adding `cargo-features = ["resolver"]` to the manifest
```
What can I do? Sorry, I have not much knowledge about rust and manifests.
I'm using newest Debian 11.2.
```
# cargo --version
cargo 1.46.0
# uname -m
armv7l
```
Thanks for your work!

**Comment by exquo** [comment]
I think this was meant for the upstream (https://github.com/signalapp/libsignal-client/), right?

**Comment by egabosh** [comment]
I think so.
Followed these instructions:
https://github.com/AsamK/signal-cli/wiki/Provide-native-lib-for-libsignal
Goal is to get a running signal-cli on my armv7l device.

**Comment by exquo** [comment]
This repo already has the library builds in the [releases](https://github.com/exquo/signal-libs-build/releases/tag/libsignal-client_v0.11.0). You don't need to run `build` / `cargo`. Just download the `..armv7..` file and swap it out in signal-cli's included `.jar` following instructions in the [readme](https://github.com/exquo/signal-libs-build#how-to-use-it) (you only need `libsignal-client`, the `zkgroup` lib is now part of it).

**Comment by egabosh** [comment]
Ah, thanks a lot. It works! :-)
