### ISSUE TITLE
Pipeline for 0.19.3 failed

### ISSUE THREAD

**Issue by morph027** [exquo/signal-libs-build#9]
https://github.com/exquo/signal-libs-build/releases/tag/libsignal-client_v0.19.3 Is missing it's assets as https://github.com/exquo/signal-libs-build/actions/runs/2844397155 failed.

**Comment by morph027** [comment]
Looks like i686-unknown-linux-gnu and armv7-unknown-linux-gnueabihf are not compiling any more due to missing support in boringssl. Probably just remove them from the workflow config and README?

**Comment by pem-imre** [comment]
This is blocking for me too.

**Comment by morph027** [comment]
I've added my own builds to https://gitlab.com/packaging/libsignal-client/ ;) (only amd64 and arm64)

**Comment by git-developer** [comment]
Excerpt from the [build log](https://github.com/exquo/signal-libs-build/runs/8167116657?check_suite_focus=true#step:11:556):
```
      /usr/bin/ld: cannot find Scrt1.o: No such file or directory
      /usr/bin/ld: cannot find crti.o: No such file or directory
      /usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-linux-gnu/7/libgcc.a when searching for -lgcc
      /usr/bin/ld: cannot find -lgcc
      /usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-linux-gnu/7/libgcc.a when searching for -lgcc
      /usr/bin/ld: cannot find -lgcc
```

A possible cause is that the compiler target is 32 bit but the machine has only libraries for 64 bit (e.g. stated on [StackOverflow](https://stackoverflow.com/questions/6329887/compiling-problems-cannot-find-crt1-o)).

Could this be the problem here?

**Comment by piramiday** [comment]
hello @exquo, any thoughts on this? new releases do not upload the required libraries anymore. :confused:

**Comment by exquo** [comment]
Sorry I have not had the time to look into this! Will try to, as soon as I can.

**Comment by share-me** [comment]
signal-cli not working anymore on Raspberry (armv7) 
"Error while checking account +**************: StatusCode: 499"

We have to upgrade signal-cli on 0.11.4
Unfortunately, libsignal-client_v0.20.0 is not available for now

I hope @exquo will save us soon

For now, keep posting mail letters  :-)

**Comment by morph027** [comment]
I've added a section on how to build armv7 using docker + qemu on non-native machines: https://gitlab.com/packaging/libsignal-client/#armv7-builds

Attached the build. Will possibly add armv7 builds to my pipelines as well.
[libsignal_jni.so-v0.20.0-armv7-unknown-linux-gnueabihf.tar.gz](https://github.com/exquo/signal-libs-build/files/9887485/libsignal_jni.so-v0.20.0-armv7-unknown-linux-gnueabihf.tar.gz)

**Comment by morph027** [comment]
🎉

**Comment by exquo** [comment]
I have made the changes to allow the [boring](https://github.com/signalapp/boring) dependency to be built. Now the `aarch64` and `i686` Linux targets do build successfully. But the `armv7` still fails.. :(. Let's track the `armv7` situation in a separate ticket: #13.

Thanks @morph027 for all your work here! And my apologies for not being available to release this sooner!
